name: Cypress E2E Tests

on:
  workflow_dispatch:

  schedule:
    - cron: "0 1 * * *"

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome
        env:
          CYPRESS_BASE_URL: https://hoohooli.gr
          CYPRESS_PRODUCT_PATH: ${{ vars.PRODUCT_PATH }}
          CYPRESS_PRODUCT_PRICE: ${{ vars.PRODUCT_PRICE }}

      - name: Send Email Notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Hoohooli - Cypress Tests Failed!"
          body: |
            The Cypress tests have failed in ${{ github.repository }} repository on the ${{ github.ref }} branch.
          to: "kapantzak@gmail.com"
          cc: "hoohooligr@gmail.com"
          from: "no-reply@github.com"

      - name: Upload Cypress screenshots and videos on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
