name: Debug

on:
  workflow_dispatch:

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Hoohooli - Cypress Tests Failed!"
          body: |
            Product path is ${{ vars.PRODUCT_PATH }}.
          to: "kapantzak@gmail.com"
          cc: "hoohooligr@gmail.com"
          from: "no-reply@github.com"
