name: Debug

on:
  workflow_dispatch:

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secrets (for testing only)
        run: |
          if [ -z "${{ secrets.SMTP_USERNAME }}" ]; then
              echo "MY_SECRET_1 is not set."
          else
              echo "MY_SECRET_1 is set."
          fi
